import { Inter, Poppins, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./context/VideoProvider";

export const inter = Inter({
  subsets: ["latin"],
});

export const source_code_pro = Source_Code_Pro({
  subsets: ["latin"],
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "300"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
